# Generated by Django 5.2.7 on 2025-11-06 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('apepaterno', models.CharField(max_length=100)),
                ('apematerno', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('alergias', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('apepaterno', models.CharField(max_length=100)),
                ('apematerno', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('ocupacion', models.CharField(max_length=100)),
                ('alergias', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.CharField(blank=True, max_length=20, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cuidados', models.TextField(blank=True, null=True)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('especie', models.CharField(max_length=50)),
                ('alimentacion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Imagen de la mascota')),
                ('dueno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animales_poseidos', to='app_mascotas.cliente')),
                ('empleados_responsables', models.ManyToManyField(blank=True, related_name='animales_a_cargo', to='app_mascotas.empleado')),
            ],
        ),
    ]
